version: 2.1

orbs:
  android: circleci/android@2.3.0

jobs:
  build:
    executor:
      name: android/android-machine
      tag: 2023.09.1
    steps:
      - checkout
      - run:
          name: Set Gradle permissions
          command: chmod +x ./gradlew
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Build APK (Release)
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release-apk

workflows:
  build-workflow:
    jobs:
      - build