version: 2.1

jobs:
  build:
    machine:
      image: android:2023.09.1
    steps:
      - checkout
      - run:
          name: Set Gradle permissions
          command: chmod +x ./gradlew
      - run:
          name: Clean Project
          command: ./gradlew clean
      - run:
          name: Build APK (Release)
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
          destination: release-apk

workflows:
  build-workflow:
    jobs:
      - build